### ISSUE TITLE
Table column truncated in the EPAS PDF page 1133

### ISSUE THREAD

**Issue by abhilasha-narendra** [EnterpriseDB/docs#1468]
## Summary![image](https://user-images.githubusercontent.com/53602601/121930159-ab08cd00-cd5f-11eb-89cd-f79d3a6db868.png)
The EPAS PDF downloaded from Docs 2.0 site has a wide table that has its right-most column truncated.

## Where did you see the problem?

The table on page 1133 of the PDF has this issue, but there can be more tables with similar issues.

## Expected behavior
 Properly formatted table

## Screenshots
Attached with the issue

**Comment by jericson-edb** [comment]
I bumped the font size down to 20px for tables, which seems to be sufficient for this table:

![image](https://user-images.githubusercontent.com/83660216/121948682-66077b00-cd0c-11eb-8cf5-c5f579f08a1e.png)

Specifically I changed the font size for tables when converting to PDFs. But looking at [the web version](https://www.enterprisedb.com/docs/epas/latest/epas_guide/03_database_administration/01_configuration_parameters/02_summary_of_configuration_parameters/) the last column is cut off in my window size and it's not immediately clear that it was missing. Maybe we should make the font smaller for HTML too.

**Comment by yujfujita** [comment]
Thank you for working on this.
And sorry to jump in here.
Yes, I agree that html font size should be smaller.
Better solution to this problem, in my opinion, will be to set up not to allow horizontal scrolling and make table adjusted to the page size.  Sorry, I do not have the knowledge on how to do this. But it was performed and solved when we used Sphinx platform.
Because, as far as  I saw, current pdf is generated from html display and that is the root cause of cut off.
Unless this is solved, we may have same cut off at other table in other pages.

Also,
Will you look at "code block" as well?
Current html in code block allows the horizontal scrolling as well. This also cause the cut off in pdf as well.
Long command line sometime overflow and will be cut in pdf documents.
Sorry, just pointing the issues and not solutions.

Again many thanks for working on this.
Yuji

**Comment by jericson-edb** [comment]
> Better solution to this problem, in my opinion, will be to set up not to allow horizontal scrolling in html and make table adjusted to the page size in html. Sorry, I do not have the knowledge on how to do this. But it was performed and solved when we used Sphinx platform.

Another option would be to reorganize the tables to have fewer or smaller columns. For instance, we could use a code for Authorized User instead of the words which could reduce the column width. Or refactor the table to be separate tables for each type of Authorized User. Those would likely be better solutions for using the tables too. Changing the font size is a quicker solution to fix the immediate problem.

I'll take a look at the [Sphinx documentation](https://www.sphinx-doc.org/en/master/) to see how they addressed this issue.

> Will you look at "code block" as well?
> Current html in code block allows the horizontal scrolling as well. This also cause the cut off in pdf as well.
> Long command line sometime overflow and will be cut in pdf documents.

That's an excellent point! We could do the font size change as a stop-gap, but it might be better to either find a way to automatically wrap long lines or edit code examples to be shorter. It might help if you had an example or two for us to look at in testing.

> Sorry, just pointing the issues and not solutions.

This is really helpful, though. Solutions are no good if they don't get at the underlying problems!
