### ISSUE TITLE
Regarding /supported-open-source/postgresql/installer/03_using_stackbuilder.mdx

### ISSUE THREAD

**Issue by dbaparesh** [EnterpriseDB/docs#1685]
## Summary

1. Where to download stack builder?
2. What if one doesn't have access to internet or proxy from machine?

## Where would you like to see this added?

At appropriate location

## Rationale

Couldn't find any legit link which I can trust to download stack builder. In production zone, access to internet is totally prohibited, not even through proxy.

**Comment by drothery-edb** [comment]
Thank you for your feedback.

To answer your first question, StackBuilder Plus (SBP) is not offered as an individual installer and is bundled within the Advanced Server Interactive Installer (available from the Downloads section). When you begin the install process for Advanced Server, you have the option to choose the products  and SBP is one of them. You can install SBP with other products or choose to have it independently installed on the system as well (without local server). More details on the graphical installer can be found in the installation guide for windows. Please note that SBP is only available for graphical installers and is not offered for native packages (e.g. rpm) since they use their own repository managers (e.g. yum, dnf).

To answer your second question, to install products on a Windows machine with no direct internet access, you will have to setup SBP on a machine with internet access. SBP can be used to only download the component installers as well; theres an option to ‘skip installation’ . You can then copy them over to your other machine.

EDB Postgres Advanced Server Download | EDB (42 kB)
https://www.enterprisedb.com/downloads/edb-postgres-advanced-server

![select_components](https://user-images.githubusercontent.com/83650384/128888389-d78ff282-92bb-4cf2-887f-abb382fc6ed8.png)

For instructions see, [Performing a Graphical Installation on Windows](https://www.enterprisedb.com/docs/epas/12/epas_inst_windows/03_installing_advanced_server_with_the_interactive_installer/01_performing_a_graphical_installation_on_windows/url).

**Comment by josh-heyer** [comment]
Also included in the PostgreSQL installer, available here: https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
