### ISSUE TITLE
Problem with PDF for HARP - Text size is too large

### ISSUE THREAD

**Issue by dougcalobrisi** [EnterpriseDB/docs#2314]
## Summary

The font/text size in the HARP PDF is much larger than other generated PDFs.

## Where did you see the problem?

HARP PDF: https://www.enterprisedb.com/docs/static/0afb65e45f107afa6bc3de8877a8b485/harp_v2.0_documentation.pdf

## Expected behavior

Text should be the normal font weight used in other PDFs.

## Screenshots
![image](https://user-images.githubusercontent.com/390043/153242835-453a2a8c-d1b1-4ba7-a649-193bd05bce34.png)

**Comment by josh-heyer** [comment]
Funny enough: this is the font size specified for ALL the PDFs... But most of them have elements (tables) that force the page to be wider than is allowed, and so it gets scaled accordingly. 

Mentioning this not as an excuse, but because fixing this will require figuring out how to reduce the font size without making it tiny for other pages.

Related issue: #1468 

Possible fix (for both this and the related issue with tables): force tables to be no wider than 100% by forcing text to wrap at arbitrary break points. Then set font size to something reasonable for all PDFs:

```css
table { 
	word-break: break-all; 
	max-width: 100%; 
}

body {
  font-size: 10pt;
}
```
