### ISSUE TITLE
Main section for "bdr_init_physical" not returned in PGD search results

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#3105]
## Summary

Searching for "bdr_init_physical" in PGD does not find https://www.enterprisedb.com/docs/pgd/latest/overview/bdr/nodes/#bdr_init_physical

**Comment by josh-heyer** [comment]
Dug into this a bit. The section is being indexed, and in fact the page is returned in results:

![Image](https://user-images.githubusercontent.com/63653723/206359116-eebe6f16-d389-406c-977b-784f3e8e25a4.png)

We deduplicate search results, so only one result is returned per path (otherwise there'd be half a dozen or more results for that page, including one for the section). Unfortunately, in this case the section chosen for the result is less than ideal. 

Possible solutions:

- alter search ranking to prioritize headings (would improve this case potentially at the cost of others, but probably reasonable overall)
- append subheadings to the title of the page when indexing (accomplishes the above, while also providing more context for search results)
- split enormous pages such as this into smaller chunks, thus increasing the chances of a "hit" being scoped to something relevant (bdr_init_physical could quite reasonably be its own topic)

**Comment by drothery-edb** [comment]
We are going with option 3 and it will be addressed when we restructure the PGD docs
