### ISSUE TITLE
Move TPAexec docs to EDB Docs

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#3448]
## Summary

We should move the TPAexec docs from their current location here https://documentation.enterprisedb.com/tpa/ to the main docs site.

We need to determine where to put the link in the docs home page.

It can currently be used with any of our database distros, PEM, EFM, and repmgr. We probably need a new category, since the products it currently supports spans three product categories. @sonotley suggested something along the lines of ‘Deployment & configuration’ might work.

**Comment by sonotley** [comment]
It was pointed out to me by the dev team that the actual 'home' of the docs is currently https://github.com/EnterpriseDB/tpaexec/tree/master/docs and they are just published to the EDB portal. The team are keen to keep the GitHub copy as the master especially because when the project is open-sourced users will expect to find docs in GitHub. Do we have a way we could simply take the existing markdown from GitHub and publish it on docs?

**Comment by sonotley** [comment]
Is there any chance we could publish these docs (or just a subset of them to meet the immediate need?) before the PGD5 release on 21st February.

**Comment by sonotley** [comment]
FYI, we already have a job to push the docs but apparently it needs a corresponding part on your end. https://github.com/EnterpriseDB/tpaexec/pull/475

**Comment by josh-heyer** [comment]
Working on this @sonotley - initial import is here: https://github.com/EnterpriseDB/docs/pull/3626
