### ISSUE TITLE
Reference implementations for CAMO in PGD

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#3456]
## Summary

We're currently not including the appendix with the reference implementations for CAMO.  We might very much want those, if they can be made public (in whole or in part).

## Background info

See: 
- https://github.com/EnterpriseDB/docs/pull/3413
- https://github.com/EnterpriseDB/bdr/blob/51d1dd174ecba8281274a9d638c77fab78d3847a/docs/camo_clients.md

If we can make the whole reference implementation subtree public, awesome - use that. Otherwise, maybe do the subset shown in the former "Appendix D: CAMO Reference Client Implementations" (linked above). 

If / when we re-add this in some form, re-add a link to the Example section in camo.mdx

**Comment by drothery-edb** [comment]
@djw-m something for you to consider

**Comment by djw-m** [comment]
First thoughts - all the knowledge in this section is embedded in the code, and there's a lot of code. 500 lines of Java+. That means a code repo to go with this, which would typically be outside the domain of the docs. The code itself is commented but there's no simple examples to go with it - Both are wrapped in db exercise frameworks, so that might be something we need to modify and leverage to provide a simple explanation of what the code does practically.... it would basically follow on from https://www.enterprisedb.com/docs/pgd/latest/durability/camo/#example-1. But that all loops round to the status of that code - is it an example (at the size of it, I'd suggest not) or is it a reference library.

**Comment by drothery-edb** [comment]
Decided to leave these behind a fire wall
