### ISSUE TITLE
Test integration with LaunchDarkly feature flags for BigAnimal 

### ISSUE THREAD

**Issue by josh-heyer** [EnterpriseDB/docs#3524]
Set up a testing branch that we can use to assess the possibility and utility of such integration

Client key: 616ecb0bd01b5c2442f9cd0e (for dev)
Test flag: dbaas-docs-test-flag

**Comment by drothery-edb** [comment]
We decided to deprioritize this for the time being. But when we do find a good feature to try it out with, we want to look at doing a light touch with the conditionalization and instead of doing a lot of hiding and showing of conditional content, just add text noting that the feature is not GA yet. A good feature for the prototype is one where there is a well defined plan around the use of the feature flag. 

@josh-heyer please add further clarification if I didn't quite capture our discussion correctly.
