### ISSUE TITLE
Regarding /pg_extensions/advanced_storage_pack/using.mdx

### ISSUE THREAD

**Issue by abip-sjarbini** [EnterpriseDB/docs#3686]
## Summary
Advanced example guidance doesn't work as expected

Version:
 PostgreSQL 15.2 (EnterpriseDB Advanced Server 15.2.0) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
, 64-bit

## Where did you see the problem?
USING autocluster is required to create nyse_trade
After inserting into nyse_trade_symbol, nyse_trade table stays empty

## Expected behavior
select ctid, * from nyse_trade gives result

## Screenshots
![image](https://user-images.githubusercontent.com/102211786/219907967-03749cbf-fd3c-4f72-bcc5-423176ced5d6.png)

## Browser / Platform
N/A

## Additional notes
N/A

**Comment by drothery-edb** [comment]
Thanks for the feedback. We are looking into this.

**Comment by ccestes** [comment]
The `select ctid, * from nyse_trade` command returns no output because the static data has been shortened for brevity in the example. So instead of inserting the full list of stock exchange symbols, numbers, and trades, the user is prompted to insert a shortened list, which doesn't include the data in the final output. 

However, the fact that the data is shortened is unclear to the user, so we plan to explain that better in the documentation and make all the data accessible in GitHub or elsewhere.

**Comment by ccestes** [comment]
@josh-heyer Here is the file for the full example. The data sets are under `INSERT INTO` commands. 
https://drive.google.com/file/d/19xhng1Q5z0JhA1iMZ-OzwhKpuXd4qoXg/view?usp=sharing

**Comment by josh-heyer** [comment]
Arthur is working on this now: https://edb.slack.com/archives/CU5QEU5L7/p1693314872322199

**Comment by tureba** [comment]
I've submitted PR https://github.com/EnterpriseDB/docs/pull/4805 with a possible way of improving the examples. Reviews are much appreciated.
