### ISSUE TITLE
Feedback on tpa 23 - "Upgrading your cluster"

### ISSUE THREAD

**Issue by nick-ivanov-edb** [EnterpriseDB/docs#5234]
### Summary

It is not clear from the upgrade command documentation that it will _not_ perform a major version Postgres upgrade (although it will perform a major version BDR upgrade), perhaps it will be useful to state the limitation explicitly. 

Also, the recommendation to use `enable_proxy_monitoring` only applies when upgrading from PGD4 to PGD5, as it only works if HARP proxies are present in the cluster. Attempts to set this property when upgrading a PGD5 cluster to a newer version will cause the process to fail.

### Where did you see the problem?

https://github.com/EnterpriseDB/docs/blob/main/product_docs/docs/tpa/23/tpaexec-upgrade.mdx

### Expected behavior

Needs clarity about the current limitations of the upgrade process

**Comment by josh-heyer** [comment]
The 2nd issue seems... Ambiguous. Before removing the recommendation, it'd be good to establish that this is NOT intended to be supported, given there seems to have been work done in this area as recently as July. Created TPA-669 to track this question.

Agree we should be explicit about the PG version upgrade caveats. Created TPA-668 so that we don't lose track of that need.
