### ISSUE TITLE
Full page or wide modal for Katacoda tutes

### ISSUE THREAD

**Issue by bradnoble** [EnterpriseDB/docs#66]
This is too jammed up:

![image](https://user-images.githubusercontent.com/1653320/88306524-d5c9dd00-ccd8-11ea-97f5-b9ef97f2313e.png)

**Comment by cero-miedo** [comment]
## Problem Statement

The center content area isn't big enough to comfortably render Katacoda tutorials. Crucial information in the inset left column is difficult to read, even at desktop size. On smaller screen devices, the problem is compounded and the user experience is poor.

## Suggested Solution

* Make the Katacoda component smarter (measure the width of the user's screen using [React Media Hook](https://github.com/lessmess-dev/react-media-hook))
* If the screen width is too small, offer to open it in a fullscreen modal, rather than a direct embed.
* Tweak the layout to allow Katacoda to be wider on desktop
* For mobile users, use contextual messaging to explain that if the user is on mobile, they may want to return on a wider viewport to experience the demo.

**Comment by epbarger** [comment]
Here's my thinking on this...

1. On mobile (which we aren't really supporting right now anyway), we can show a nice message, like you said. We'll just do a basic css media query to hide/show the message based on window size, and still let you start the tutorial if you want.

2. On desktop we can have the tutorial break out of the container to use the full width of the "main" area. Something like this...

<img width="1680" alt="Screen Shot 2020-07-28 at 2 17 13 PM" src="https://user-images.githubusercontent.com/2780987/88705473-94bd3880-d0dd-11ea-9ea9-cdf25fde7018.png">

I think it would have to overlay the table of contents, but that's probably not a big deal. This would be a little strange to code since we have the break the embed out of the document structure, but I think it's achievable with some javascript to calculate the correct positioning.

I'm not sure I understand the need for a fullscreen modal, since you can already make katacoda fullscreen with that icon in the top right of the embed. Though I suppose we can add a message about trying fullscreen if your screen size is under some px threshold

**Comment by cero-miedo** [comment]
## Desktop

![Desktop HD](https://user-images.githubusercontent.com/62722976/89043444-655a3600-d340-11ea-9f88-21bccb1b8508.png)

## Tablet

![Tablet](https://user-images.githubusercontent.com/62722976/89043496-7b67f680-d340-11ea-8751-21fe30f1f557.png)
![Tablet Copy](https://user-images.githubusercontent.com/62722976/89043542-8ae73f80-d340-11ea-86f7-677e97133fa9.png)

## Mobile

![Mobile](https://user-images.githubusercontent.com/62722976/89043590-9c304c00-d340-11ea-9f60-5eadc5f91d5f.png)
